name: DAST-Vercel

on:
  pull_request:
    branches:
      - '**'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Vercel Preview URL (commit → PR → latest)
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          TEAM_ARG=""
          if [ -n "${VERCEL_TEAM_ID:-}" ]; then TEAM_ARG="&teamId=$VERCEL_TEAM_ID"; fi

          JSON=$(curl -fsSL -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v6/deployments?app=$VERCEL_PROJECT&target=preview&limit=100$TEAM_ARG")

          echo "—— latest five ——"
          echo "$JSON" | jq -r '.deployments[0:5][] | {url,state,target,meta:{githubCommitSha,githubPrId}}'


          URL=$(echo "$JSON" | jq -r --arg SHA "$HEAD_SHA" \
            '.deployments[] | select(.meta.githubCommitSha == $SHA) | .url' | head -n1)


          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            URL=$(echo "$JSON" | jq -r --argjson PR "$PR_NUMBER" \
              '.deployments[] | select(.meta.githubPrId == $PR) | .url' | head -n1)
          fi


          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            URL=$(echo "$JSON" | jq -r \
              '.deployments | sort_by(.createdAt // .created) | reverse | .[0].url')
          fi

          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            echo "cannot find Preview URL"
            exit 1
          fi

          echo "preview=https://$URL" >> "$GITHUB_OUTPUT"
          echo "✅ Found preview: https://$URL"


      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
         target: ${{ steps.vercel.outputs.preview }}
         fail_action: false
         allow_issue_writing: false



      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
         name: zap-scan          
         path: report_html.html
               report_json.json
               report_md.md
         retention-days: 14