name: DAST-Vercel

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  actions: write   # 允许创建 artifact 容器（同仓 PR 必要）

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... 省略：你的 Get Vercel Preview URL 步骤 ...

      # ★ 关键：显式把 artifact_name 设为空字符串 => 完全禁用 ZAP 内置上传
      - name: ZAP Baseline Scan (no built-in artifact upload)
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: ${{ steps.vercel.outputs.preview }}/healthz   # 请确保这个是公开 200
          cmd_options: -a
          allow_issue_writing: false
          rules_file_name: .zap/rules.tsv
          artifact_name: ""   # <= 关闭内置上传，避免“Artifact name is valid!”那条

      - name: List ZAP outputs
        run: ls -lah && echo && ls -lah report* || true

      # 仅同仓 PR 才手动上传；fork PR 跳过（很多组织策略下 fork 无法创建 artifact）
      - name: Upload ZAP reports (manual)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: zap-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: |
            **/report_html.html
            **/report_json.json
            **/report_md.md
          if-no-files-found: error

      # 无论是否上传，都在 Summary 内联一张图，保证可见性
      - name: Inline screenshot in Summary
        run: |
          sudo apt-get update && sudo apt-get install -y wkhtmltopdf
          FILE=$(ls -1 **/report_html.html 2>/dev/null | head -n1 || true)
          if [ -n "$FILE" ]; then
            wkhtmltoimage --width 1200 "$FILE" zap-summary.png
            B64=$(base64 -w0 zap-summary.png)
            {
              echo "## DAST / ZAP Summary"
              echo "**Target:** ${{ steps.vercel.outputs.preview }}"
              echo "<details><summary>Report screenshot</summary>"
              echo "<img src='data:image/png;base64,${B64}' alt='ZAP'/>"
              echo "</details>"
              if [ "${{ github.event.pull_request.head.repo.full_name == github.repository }}" = "true" ]; then
                echo "Full HTML/JSON/MD report: see **Artifacts** on the right."
              else
                echo "_Fork PR: artifact upload skipped by policy; screenshot shown above._"
              fi
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No report_html.html found" >> "$GITHUB_STEP_SUMMARY"
          fi
